### PR TITLE
Some language correction

### PR DESCRIPTION
**Pull request by fay-jai**

### CODE REVIEW

**Comment by iliakan** [comment]
Are you a native speaker? Are you sure?

**Comment by fay-jai** [comment]
Yes I'm a native speaker :)

**Comment by iliakan** [comment]
Uhm, maybe like this is better? 
"The `document` object gives access to the page content"

**Comment by fay-jai** [comment]
Sure that sounds good too!

**Comment by iliakan** [comment]
Okay, fixing that, thank you!

**Pull request closed without merging**
