### PR TITLE
Update article.md

### PR DESCRIPTION
**Pull request by burkehavendesign**
That English is not idiomatic at all.  You could says:

"Why don't you take a math class?"
or
"How about taking a math class?"

Also, you may want to consider using American English, and in this case, please use "math" not "maths".  The US is a bigger market than the UK, is more widely used, the US is the center of the tech industry, etc.  The standard for using English-language variables in code comes from the US, not England.  And British-English is annoying. ;) :)

### CODE REVIEW

**Comment by iliakan** [comment]
Thank you very much, I'm mostly using American English, but far from perfect in it.

**Comment by iliakan** [comment]
The PR would ruin the code though, because of nested quotes.

**Comment by burkehavendesign** [comment]
That's good to know.  
I found another non-idiomatic phrase, but it is in "Tasks" so I can't edit it.
Please see "The Javascript language -> Javascript Fundamentals -> Functions -> Tasks"
There is a phrase in the first task, "Did parents allow you?"
You could change that to one of the following:   
   - "Do you have your parents permissions?"
   - "Do you have your parents permission to access this page?"


 __________________________________________
Christine Hill781-934-2420 

    On Friday, April 7, 2017 1:03 PM, Ilya Kantor <notifications@github.com> wrote:
 

 Thank you very much, I'm mostly using American English, but far from perfect in it.—

**Comment by iliakan** [comment]
`Do you have your parents permission to access this page?` -- can the phrase be made shorter?

**Pull request merged**
